# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='板块名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间 ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间 ')),
            ],
            options={
                'verbose_name_plural': '帖子',
                'verbose_name': '帖子',
            },
        ),
    ]
