# Generated by Django 2.0rc1 on 2017-11-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20171111_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_time'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
    ]
