# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
