# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171203_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
