# Generated by Django 2.0.5 on 2018-05-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180527_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comments', verbose_name='@'),
        ),
    ]
